### ISSUE TITLE
Separating environment specific details 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/odh#36]
We are already starting to see some `moc` specific implementation (e.g. storage class for JH #22 and possibly superset #35). We need a way to separate these out from general deployments. 

We could separate them out into bases/overlays (where overlays have folders like `moc` and `quicklab`). The problem is then our `argocd-apps` repo will become environment specific (since we specify a `path`). As a solution we could also extend the base/overlays structure to the `argocd-apps` repo. That's one suggestion, open to other ideas.

**Comment by tumido** [comment]
I kinda agree with you. It's not pretty but it sounds like a viable strategy and I have nothing better in my sleeve right now since I was thinking the same. :slightly_smiling_face:
